# test
language: python
python:
  - "3.5"
before_script:
  - cp settings/database.sample.yaml settings/database.yaml
  - cp settings/htsohm.sample.yaml settings/htsohm.yaml
install: "pip install -r requirements.txt"
script:
  - pytest
